# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: memkv.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmemkv.proto\x12\x05memkv\"\x1a\n\nGetCommand\x12\x0c\n\x04keys\x18\x01 \x03(\t\"1\n\nSetCommand\x12#\n\nkey_values\x18\x01 \x03(\x0b\x32\x0f.memkv.KeyValue\"\x1d\n\rDeleteCommand\x12\x0c\n\x04keys\x18\x01 \x03(\t\"&\n\x08KeyValue\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\"\xab\x01\n\x0eMetricsCommand\x12\x15\n\rget_key_count\x18\x01 \x01(\x08\x12%\n\x1dget_total_store_contents_size\x18\x02 \x01(\x08\x12\x1b\n\x13get_keys_read_count\x18\x03 \x01(\x08\x12\x1e\n\x16get_keys_updated_count\x18\x04 \x01(\x08\x12\x1e\n\x16get_keys_deleted_count\x18\x05 \x01(\x08\"\x98\x01\n\x0fMetricsResponse\x12\x11\n\tkey_count\x18\x01 \x01(\x03\x12!\n\x19total_store_contents_size\x18\x02 \x01(\x03\x12\x17\n\x0fkeys_read_count\x18\x03 \x01(\x03\x12\x1a\n\x12keys_updated_count\x18\x04 \x01(\x03\x12\x1a\n\x12keys_deleted_count\x18\x05 \x01(\x03\"3\n\x0cKeyValueList\x12#\n\nkey_values\x18\x01 \x03(\x0b\x32\x0f.memkv.KeyValue\"\x17\n\x07KeyList\x12\x0c\n\x04keys\x18\x01 \x03(\t\"\xae\x01\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12&\n\x07kv_list\x18\x03 \x01(\x0b\x32\x13.memkv.KeyValueListH\x00\x12)\n\x07metrics\x18\x04 \x01(\x0b\x32\x16.memkv.MetricsResponseH\x00\x12\"\n\x08key_list\x18\x05 \x01(\x0b\x32\x0e.memkv.KeyListH\x00\x42\n\n\x08\x63ontentsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'memkv_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETCOMMAND._serialized_start=22
  _GETCOMMAND._serialized_end=48
  _SETCOMMAND._serialized_start=50
  _SETCOMMAND._serialized_end=99
  _DELETECOMMAND._serialized_start=101
  _DELETECOMMAND._serialized_end=130
  _KEYVALUE._serialized_start=132
  _KEYVALUE._serialized_end=170
  _METRICSCOMMAND._serialized_start=173
  _METRICSCOMMAND._serialized_end=344
  _METRICSRESPONSE._serialized_start=347
  _METRICSRESPONSE._serialized_end=499
  _KEYVALUELIST._serialized_start=501
  _KEYVALUELIST._serialized_end=552
  _KEYLIST._serialized_start=554
  _KEYLIST._serialized_end=577
  _RESPONSE._serialized_start=580
  _RESPONSE._serialized_end=754
# @@protoc_insertion_point(module_scope)
